# Generated by Django 4.1.2 on 2022-11-06 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('effect', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='')),
                ('front', models.ImageField(blank=True, null=True, upload_to='')),
                ('front_shiny', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BasePokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type_1', models.CharField(choices=[('normal', 'normal'), ('fire', 'fire'), ('water', 'water'), ('grass', 'grass'), ('flying', 'flying'), ('fighting', 'fighting'), ('poison', 'poison'), ('electric', 'electric'), ('ground', 'ground'), ('rock', 'rock'), ('psychic', 'psychic'), ('ice', 'ice'), ('bug', 'bug'), ('ghost', 'ghost'), ('steel', 'steel'), ('dragon', 'dragon'), ('dark', 'dark'), ('fairy', 'fairy')], max_length=255)),
                ('type_2', models.CharField(blank=True, choices=[('normal', 'normal'), ('fire', 'fire'), ('water', 'water'), ('grass', 'grass'), ('flying', 'flying'), ('fighting', 'fighting'), ('poison', 'poison'), ('electric', 'electric'), ('ground', 'ground'), ('rock', 'rock'), ('psychic', 'psychic'), ('ice', 'ice'), ('bug', 'bug'), ('ghost', 'ghost'), ('steel', 'steel'), ('dragon', 'dragon'), ('dark', 'dark'), ('fairy', 'fairy')], max_length=255, null=True)),
                ('base_hp', models.IntegerField()),
                ('base_att', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('base_sp_att', models.IntegerField()),
                ('base_sp_def', models.IntegerField()),
                ('base_spd', models.IntegerField()),
                ('tier', models.CharField(choices=[('UBER', 'Uber'), ('OU', 'Overused'), ('UUBL', 'Underused Borderline'), ('UU', 'Underused'), ('RUBL', 'Rarelyused Borderline'), ('RU', 'Rarelyused'), ('NUBL', 'Neverused Borderline'), ('NU', 'Neverused'), ('PU', 'PU'), ('U', 'Untiered'), ('NA', 'n/a')], default='U', max_length=255, null=True)),
                ('ability_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ability_1', to='core.ability')),
                ('ability_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_2', to='core.ability')),
                ('ability_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_3', to='core.ability')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.art')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=55, null=True)),
                ('nature', models.CharField(choices=[('ADAMANT', 'Adamant'), ('MODEST', 'Modest')], max_length=255, null=True)),
                ('held_item', models.CharField(blank=True, max_length=255, null=True)),
                ('ivs_hp', models.IntegerField(default=31)),
                ('ivs_att', models.IntegerField(default=31)),
                ('ivs_def', models.IntegerField(default=31)),
                ('ivs_sp_att', models.IntegerField(default=31)),
                ('ivs_sp_def', models.IntegerField(default=31)),
                ('ivs_spd', models.IntegerField(default=31)),
                ('evs_hp', models.IntegerField(default=0)),
                ('evs_att', models.IntegerField(default=0)),
                ('evs_def', models.IntegerField(default=0)),
                ('evs_sp_att', models.IntegerField(default=0)),
                ('evs_sp_def', models.IntegerField(default=0)),
                ('evs_spd', models.IntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ability')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.basepokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sprite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.art')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('match_format', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.username')),
                ('pk_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pk_1', to='core.custompokemon')),
                ('pk_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_2', to='core.custompokemon')),
                ('pk_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_3', to='core.custompokemon')),
                ('pk_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_4', to='core.custompokemon')),
                ('pk_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_5', to='core.custompokemon')),
                ('pk_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_6', to='core.custompokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('match_format', models.CharField(max_length=255)),
                ('gametype', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('p1_pk_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_1', to='core.basepokemon')),
                ('p1_pk_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_2', to='core.basepokemon')),
                ('p1_pk_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_3', to='core.basepokemon')),
                ('p1_pk_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_4', to='core.basepokemon')),
                ('p1_pk_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_5', to='core.basepokemon')),
                ('p1_pk_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_6', to='core.basepokemon')),
                ('p2_pk_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_1', to='core.basepokemon')),
                ('p2_pk_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_2', to='core.basepokemon')),
                ('p2_pk_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_3', to='core.basepokemon')),
                ('p2_pk_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_4', to='core.basepokemon')),
                ('p2_pk_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_5', to='core.basepokemon')),
                ('p2_pk_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_6', to='core.basepokemon')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to='core.username')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to='core.username')),
                ('teams', models.ManyToManyField(blank=True, related_name='matches', to='core.customteam')),
                ('victor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='victor', to='core.username')),
            ],
        ),
    ]
