# Generated by Django 4.1.2 on 2022-10-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sprite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sprite')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sprite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sprite')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dex_number', models.IntegerField()),
                ('sprite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sprite')),
                ('type_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_1', to='core.pokemontype')),
                ('type_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_2', to='core.pokemontype')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('match_format', models.CharField(max_length=255)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to='core.username')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to='core.username')),
                ('victor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='victor', to='core.username')),
            ],
        ),
    ]
