# Generated by Django 4.1.2 on 2022-11-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='matches', to='core.customteam'),
        ),
    ]
