# Generated by Django 4.1.2 on 2022-10-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_username_sprite'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
