# Generated by Django 4.1.2 on 2022-10-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_art_ability_effect_alter_ability_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemontype',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pokemontype',
            name='sprite',
        ),
    ]
