# Generated by Django 4.1.2 on 2022-10-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_art_ability_effect_alter_ability_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='effect',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
