# Generated by Django 4.1.2 on 2022-10-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_basepokemon_sprite_basepokemon_artwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basepokemon',
            name='dex_number',
        ),
        migrations.AlterField(
            model_name='art',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
