# Generated by Django 4.1.2 on 2022-10-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_basepokemon_dex_number_alter_art_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepokemon',
            name='type_1',
            field=models.CharField(choices=[('normal', 'normal'), ('fire', 'fire'), ('water', 'water'), ('grass', 'grass'), ('flying', 'flying'), ('fighting', 'fighting'), ('poison', 'poison'), ('electric', 'electric'), ('ground', 'ground'), ('rock', 'rock'), ('psychic', 'psychic'), ('ice', 'ice'), ('bug', 'bug'), ('ghost', 'ghost'), ('steel', 'steel'), ('dragon', 'dragon'), ('dark', 'dark'), ('fairy', 'fairy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='basepokemon',
            name='type_2',
            field=models.CharField(choices=[('normal', 'normal'), ('fire', 'fire'), ('water', 'water'), ('grass', 'grass'), ('flying', 'flying'), ('fighting', 'fighting'), ('poison', 'poison'), ('electric', 'electric'), ('ground', 'ground'), ('rock', 'rock'), ('psychic', 'psychic'), ('ice', 'ice'), ('bug', 'bug'), ('ghost', 'ghost'), ('steel', 'steel'), ('dragon', 'dragon'), ('dark', 'dark'), ('fairy', 'fairy')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PokemonType',
        ),
    ]
