# Generated by Django 4.1.2 on 2022-10-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_basepokemon_type_1_alter_basepokemon_type_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepokemon',
            name='ability_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_2', to='core.ability'),
        ),
        migrations.AlterField(
            model_name='basepokemon',
            name='ability_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_3', to='core.ability'),
        ),
    ]
