# Generated by Django 4.1.2 on 2022-10-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_basepokemon_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepokemon',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='basepokemon',
            name='tier',
            field=models.CharField(choices=[('UBER', 'Uber'), ('OU', 'Overused'), ('UUBL', 'Underused Borderline'), ('UU', 'Underused'), ('RUBL', 'Rarelyused Borderline'), ('RU', 'Rarelyused'), ('NUBL', 'Neverused Borderline'), ('NU', 'Neverused'), ('PU', 'PU'), ('U', 'Untiered'), ('NA', 'n/a')], default='Untiered', max_length=255),
        ),
    ]
