# Generated by Django 4.1.2 on 2022-10-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_basepokemon_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompokemon',
            name='nickname',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='basepokemon',
            name='ability_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_2', to='core.ability'),
        ),
        migrations.AlterField(
            model_name='basepokemon',
            name='ability_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_3', to='core.ability'),
        ),
        migrations.AlterField(
            model_name='basepokemon',
            name='type_2',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('fire', 'fire'), ('water', 'water'), ('grass', 'grass'), ('flying', 'flying'), ('fighting', 'fighting'), ('poison', 'poison'), ('electric', 'electric'), ('ground', 'ground'), ('rock', 'rock'), ('psychic', 'psychic'), ('ice', 'ice'), ('bug', 'bug'), ('ghost', 'ghost'), ('steel', 'steel'), ('dragon', 'dragon'), ('dark', 'dark'), ('fairy', 'fairy')], max_length=255, null=True),
        ),
    ]
