# Generated by Django 4.1.2 on 2022-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_art_artwork_alter_art_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepokemon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
