# Generated by Django 4.1.2 on 2022-11-02 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_basepokemon_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='p1_pk_1',
            field=models.ForeignKey(default=150, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_1', to='core.basepokemon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='p1_pk_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_2', to='core.basepokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='p1_pk_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_3', to='core.basepokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='p1_pk_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_4', to='core.basepokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='p1_pk_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_5', to='core.basepokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='p1_pk_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_pk_6', to='core.basepokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='p2_pk_1',
            field=models.ForeignKey(default=151, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_1', to='core.basepokemon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='p2_pk_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_2', to='core.basepokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='p2_pk_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_3', to='core.basepokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='p2_pk_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_4', to='core.basepokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='p2_pk_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_5', to='core.basepokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='p2_pk_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_pk_6', to='core.basepokemon'),
        ),
    ]
