# Generated by Django 4.1.2 on 2022-11-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_battle_p1_pk_1_battle_p1_pk_2_battle_p1_pk_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='gametype',
            field=models.CharField(default='singles', max_length=255),
            preserve_default=False,
        ),
    ]
