# Generated by Django 4.1.2 on 2022-11-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_battle_gametype'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompokemon',
            name='held_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CustomTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('match_format', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.username')),
                ('pk_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pk_1', to='core.custompokemon')),
                ('pk_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_2', to='core.custompokemon')),
                ('pk_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_3', to='core.custompokemon')),
                ('pk_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_4', to='core.custompokemon')),
                ('pk_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_5', to='core.custompokemon')),
                ('pk_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pk_6', to='core.custompokemon')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='matches', to='core.customteam'),
        ),
        migrations.AddField(
            model_name='battle',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.customteam'),
        ),
    ]
